[package]
name = "aurora-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.123.1"
cranelift-module = "0.123.1"
cranelift-preopt = "0.92.1"
target-lexicon = "0.13.2"
cranelift-object = "0.123.1"
cranelift-codegen = "0.123.1"
cc = "1.0.98"
current_platform = "0.2.0"
